version: '3.8'

services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  daphne:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8001 django_app.asgi:application
    expose:
      - 8001
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    
volumes:
  postgres_data:
