version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    
volumes:
  postgres_data: